spring:
  application:
    name: todoapp
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: todoappuser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 2de6a582fbbd1db0a1a68e978d062a58616c6db083a2ee81db2521bf6e3f39cb
cors:
  allowed-origins:
    - http://localhost:5173
    - https://localhost:5173
    - http://localhost
    - https://localhost
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE